"""add pessoas_json to cotacao

Revision ID: 42620e64cc95
Revises: 97f19e0f6733
Create Date: 2025-05-30 13:50:35.998113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42620e64cc95'
down_revision = '97f19e0f6733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cotacao', sa.Column('pessoas_json', sa.Text(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cotacao', 'pessoas_json')
    # ### end Alembic commands ###
