"""add estado_civil to cotacao

Revision ID: ad8d82eb3cbe
Revises: 
Create Date: 2025-05-23 22:05:01.049438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8d82eb3cbe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacao', schema=None) as batch_op:
        batch_op.drop_column('estado_civil')

    # ### end Alembic commands ###
